### ISSUE TITLE
Help! Deployment failded

### ISSUE THREAD

**Issue by highcold** [Bitergia/fiware-devguide-app#123] opened 2016-08-09 06:45 UTC
when I finished the command "docker-compose up -d", all the components started. However I can't visit "http://tourguide", and I use "docker-compose ps" to check state of all components. The result was  **"ul20client /docker- entrypoint.sh--acpi Exit 1"**
Here is the information:
- version of TourGuide is develop
- OS is ubuntu 14.04
- Although I have fix the hosts, I can't use gist to create a gist in China. Because the log is big(1.8M), I upload [screen.log](https://github.com/highcold/docker-compose-test.git) 
  In China, the material about Fiware is rather rare, so I am urgent to get people's help.
  Thank you.

**Comment by dmabtrg** [comment] 2016-08-10 14:37
Closing as duplicate of  https://github.com/Fiware/tutorials.TourGuide-App/issues/121#issuecomment-238276167

**Closed as completed by dmabtrg** 2016-08-10 14:37 UTC
